# Generated by Django 4.0.4 on 2022-04-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='books_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.books'),
        ),
    ]
