# Generated by Django 4.0.4 on 2022-04-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_alter_isbn_books_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrders',
            fields=[
            ],
            options={
                'ordering': ['created'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orm.bookcontent',),
        ),
    ]
